config/routes.rb
CotrolGastos::Application.routes.draw do
  devise_for :users

  get "home/index"
  
  resources :services do
    resources :expenses
  end
  
  resources :shared_times
  resources :users

  root :to => 'home#index'

end

app/models/expense.rb
class Expense < ActiveRecord::Base
  validates_uniqueness_of :service_id, :scope => [ :month, :year]
  validates_numericality_of :value
  validates_numericality_of :year
  validates_inclusion_of :month, :in => 1..12, :message => "has not selected"
  belongs_to :service
end

app/models/service.rb
class Service < ActiveRecord::Base
  validates :name,  :presence => true
  
  belongs_to :user
  has_many :expenses
end

app/models/shared_time.rb
class SharedTime < ActiveRecord::Base
  attr_accessible :shared_time_user_tokens,:month,:year
  belongs_to :user
  has_many :shared_time_users
  has_many :st_users, :through => :shared_time_users, :source => :user
  attr_reader :shared_time_user_tokens
  
  def shared_time_user_tokens=(ids)
    self.st_users=User.find(ids.split(/,/))
  end
end

app/models/shared_time_user.rb
class SharedTimeUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :shared_time
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :services
  has_many :shared_times
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    #@expenses = Expense.where(:service_id => params[:format])
    @service = Service.find(params[:service_id])
    @expenses= Expense.where(:service_id => @service.id).order(:year,:month)#.paginate(:per_page => 5, :page => params[:page])
    first_expense=@expenses.first
    last_expense=@expenses.last
    
    dates=Array.new
    if @expenses.size>0
      #obtiene los meses entre los años min y max de los expenses
      dates=(Date.new(first_expense.year,first_expense.month)..Date.new(last_expense.year,last_expense.month)).select {|d| d.day == 1}

      #obtiene los values de cada uno de los meses antes obtenidos, sino tiene value se le asigna nil
      @vals=Array.new
      dates.each do |date|
        exp = Expense.where(:service_id => @service.id).where(:year =>date.year).where(:month =>date.month)
        if exp.size==0
          @vals.push(nil)
        else
          @vals.push(exp[0].value)
        end
      end
    end

    #se obtienen los meses con formato mes/año para pasarlos a la vista
    @dates=Array.new
    dates.each do |date|
      d=date.strftime("%b/%y") 
      @dates.push(d)
    end

  end
  def new
    @service = Service.find(params[:service_id])
    @expense = Expense.new
    @expense.service=@service
    puts "este ",@expense.service.id
  end
  def create
    @service = Service.find(params[:service_id])
    @expense = @service.expenses.new(params[:expense])
    respond_to do |format|
      if @expense.save
        format.html { redirect_to service_expenses_path(@service), notice: 'Expense was successfully created.' }
        format.json { render json: @expense, status: :created, location: @expense }
      else
        format.html { render action: "new" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
    
  end
  def edit
    @service = Service.find(params[:service_id])
    @expense=Expense.find(params[:id])
  end
  def update
    @service = Service.find(params[:service_id])
    @expense =Expense.find(params[:id])
    respond_to do |format|
      if @expense.update_attributes(params[:expense])
        format.html { redirect_to service_expenses_path(@expense.service), notice: 'Expense was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @expense = Expense.find(params[:id])
    @service = @expense.service
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to service_expenses_path(@service) }
      format.json { head :ok }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    puts 'entra home'
    if user_signed_in?
      st_users=SharedTimeUser.where(:user_id =>current_user.id).order("created_at DESC")
      @expenses=Array.new
      st_users.each do |st_user|
          @expenses.concat(Expense.joins(:service).where(:services =>{:user_id =>st_user.shared_time.user_id}).where(:month =>st_user.shared_time.month).where(:year =>st_user.shared_time.year))      
      end
      @expenses.each do |expense|
        p expense.service.name
      end
    else
      p "no inicio session"
      
    end
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    #@services = Service.where(:user_id =>current_user.id)
    @services = current_user.services#.paginate(:per_page => 5, :page => params[:page])
    
    @dates = Array.new
    @services.each do |service|
      service.expenses.each do |ex|
        d = DateTime.new(ex.year,ex.month,1).strftime("%b/%y") 
        @dates.push(d)
      end
    end
    @dates = @dates.uniq
  end

  def edit
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
  end
  
  def create
    @service = current_user.services.new(service_params)
    if @service.save
      redirect_to services_path, notice: 'Service was successfully created.'
    else
      render :new, alert: 'Error'
    end
  end
  
  def update
    @service =Service.find(params[:id])
    if @service.update_attributes(service_params)
      redirect_to services_path, notice: 'Service was successfully updated.'
    else
      render :edit, alert: 'Error'
    end
  end

  private

  def service_params
    params.require(:service).permit(:name)
  end
end

app/controllers/shared_times_controller.rb
class SharedTimesController < ApplicationController
  def index
    @shared_times = SharedTime.where(:user_id =>current_user.id)
    @users=User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users.map(&:attributes) }
    end
  end
  def edit
    puts params[:id]
    @shared_time = SharedTime.find(params[:id])
    @array_users=Array.new
    @shared_time.st_users.each do |user|
      hash_users=Hash.new
      hash_users['id'] = user.id
      hash_users['name']= user.email
      @array_users.push(hash_users)
    end
  end
  def new
    @shared_time = SharedTime.new
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user }
    end
  end
  def create
    @shared_time=current_user.shared_times.new(params[:shared_time])
    
    respond_to do |format|
      if @shared_time.save
        #@shared_time.st_users=params[:st_users][:user_ids] ||= []
        format.html { redirect_to shared_times_path, notice: 'Service was successfully created.' }
        format.json { render json: @shared_time, status: :created, location: @shared_time }
      else
        format.html { render action: "new" }
        format.json { render json: @shared_time.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @shared_time =SharedTime.find(params[:id])
    respond_to do |format|
      if @shared_time.update_attributes(params[:shared_time])
        format.html { redirect_to shared_times_path, notice: 'shared time was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @shared_time.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
    @array_users=Array.new
    @users.each do |user|
      hash_users=Hash.new
      hash_users['id'] = user.id
      hash_users['name']= user.email
      @array_users.push(hash_users)
    end
    
    respond_to do |format|
      format.html
      format.json { render :json => @array_users}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shared_times_helper.rb
module SharedTimesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_form.html.erb
<%= form_for([@service, @expense]) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :month %><br />
    <%= f.select :month,  options_for_select([["","0"],["January","1"],["February","2"],["March","3"],["April","4"],["May","5"],["June","6"],["July","7"],["August","8"],["September","9"],["October","10"],["November","11"],["December","12"]],@expense.month) %>

  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form' %>

app/views/expenses/index.html.erb
<script type="text/javascript" charset="utf-8">
  $(function () {
    new Highcharts.Chart({
      chart: { 
	    renderTo: 'expenses_chart' 
	  },
      title: {
	    text: 'Expenses service'
	  },
      xAxis: {
	    categories: <%=raw(@dates.to_json) %>,
	    type: 'date',labels: { style: { color: '#000', font: '9px Trebuchet MS, Verdana, sans-serif' } }
	  },
      yAxis: {
		
	    title: { text: 'Values'}
	  },
      series: [{
	    data: <%= @vals.to_json %>
      }]
    });
  });
</script>


<h1>Expenses - <%=@service.name%></h1>
<div><%=link_to "New", new_service_expense_path(@service)%></div>

<div id="expenses_chart" style="width: 100%; height: 250px;"> </div>
<table width="100%">
	<tr>
		<th style="background: #A4A4A4">Month</th>
		<th style="background: #A4A4A4">Year</th>
		<th style="background: #A4A4A4">Value</th>
		<th style="background: #A4A4A4">Created at</th>
		<th style="background: #A4A4A4">Updated at</th>
		<th colspan="2" style="background: #A4A4A4">Options</th>
	</tr>
	<% @expenses.each do |expense| %>
    	<tr>
			
			<td><%=DateTime.new(2000,expense.month,1).strftime("%B") %></td>
			<td><%= expense.year %></td>
			<td><%= expense.value %></td>
			<td><%= expense.created_at.strftime("%d/%m/%Y %H:%M:%S") %></td>
			<td><%= expense.updated_at.strftime("%d/%m/%Y %H:%M:%S") %></td>
			<td><center><%=link_to "Edit", edit_service_expense_path(@service,expense)%> </center></td>
			<td><center><%= link_to 'Delete', [@service,expense], confirm: 'Are you sure?', method: :delete %></center></td>
		
		
	<% end %>
</table>
<%#will_paginate @expenses%>

app/views/expenses/new.html.erb
<h1>New Expense - <%=@service.name%></h1>
<%= render 'form' %>

app/views/home/index.html.erb
<h1>Expenses Control - Home</h1>
<p></p>
<a href="tel:+4917640206387">+49 (0)176 - 402 063 87</a>
<a href="#">+49 (0)176 - 402 063 88</a
<%if user_signed_in?%>
<table width="100%">
	<tr>
		<th style="background: #A4A4A4">User</th>
		<th style="background: #A4A4A4">Service</th>
		<th style="background: #A4A4A4">Value</th>
		<th style="background: #A4A4A4">Month</th>
		<th style="background: #A4A4A4">Year</th>



	</tr>
	<% @expenses.each do |expense| %>
    	<tr>
	<td><%= expense.service.user.email %></td>
				<td><%= expense.service.name %></td>
				<td><%= expense.value %></td>			<td><%=DateTime.new(2000,expense.month,1).strftime("%B") %></td>
			<td><%= expense.year %></td>
			


		
		
	<% end %>
</table>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CotrolGastos</title>
  <%= stylesheet_link_tag    "application" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application" %>
  
<script type="text/javascript">
  $(function () {
  $('#shared_time_shared_time_user_tokens').tokenInput('/users.json', { crossDomain: false  ,
      prePopulate: $('#shared_time_shared_time_user_tokens').data('pre'),
  theme: 'facebook'
   });
});
</script>

</head>
<body bgcolor="#414141">
  <table width="75%" align="center" style="background:#ffffff" class="rounded-corners" height="600px">
  <tr>
    <th valign="top">
  <div id="user_nav"  >
  <% if user_signed_in? %>
     
        Signed in as <%= current_user.email %>. Not you?
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %><br>

      
        <%= link_to "Home", home_index_path %>
        <%= link_to "Services", services_path %>
        <%= link_to "Shared Times", shared_times_path %>

    <% else %>
        
      <%= link_to "Sign up", new_user_registration_path %> or
      <%= link_to "Sign in", new_user_session_path %>
        

    <% end %>
    </div>

<table width="90%" align="center" style="background:#ffffff">
  
    
  
  
  <tr>
  <th>
    <%= yield %>
  </th>
  </tr>
</table>
</th>
</tr>
</table>
  <script type='text/javascript'>
    var _sm_id = 'c77d3aa5-f0d9-4dd6-9c75-da1e8b5b85c9';
    (function() {
        var sm = document.createElement('script'); sm.type = 'text/javascript'; sm.async = true;
        sm.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'smartcontact.r13.railsrumble.com/assets/smart_contact.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sm, s);
    })();
  </script>
</body>
</html>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

app/views/services/index.html.erb
<script type="text/javascript">
		
			var chart;
			$(document).ready(function() {
				chart = new Highcharts.Chart({
					chart: {
						renderTo: 'container',
						defaultSeriesType: 'column'
					},
					title: {
						text: 'Monthly Expense'
					},
					subtitle: {
						text: 'Source: Control Expenses'
					},
					xAxis: {
						categories: <%=raw(@dates.to_json) %>
					},
					yAxis: {
						min: 0,
						title: {
							text: 'Expense (Pesos)'
						}
					},
					legend: {
						layout: 'vertical',
						backgroundColor: '#FFFFFF',
						align: 'left',
						verticalAlign: 'top',
						x: 10,
						y: 0,
						floating: true,
						shadow: true
					},
					tooltip: {
						formatter: function() {
							return ''+
								this.x +': '+ this.y +' Pesos';
						}
					},
					plotOptions: {
						column: {
							pointPadding: 0,
							borderWidth: 0,
							pointWidth: 4
						}
					},
				        series: [
				  		<%ind=1%>
				<%@services.each do |service|%>{
  							name: <%=raw(service.name.to_json)%>,
  							data: <%= service.expenses.map(&:value).to_json %>
						},
						<%end%>
				
				]
				});
				
				
			});
				
		</script>
<!--<div id="container" style="width: 1000px; height: 300px;"> </div>-->
<h1>Services</h1>
<div><%=link_to "New", new_service_path%></div>


<table width="100%">
	<tr>
		<th style="background: #A4A4A4">Name</th>
		<th style="background: #A4A4A4">Created at</th>
		<th style="background: #A4A4A4">Updated at</th>
		<th colspan="2" style="background: #A4A4A4">Options</th>
	</tr>
	<% @services.each do |service| %>
    	<tr>
			<td><%= service.name %></td>
			<td><%= service.created_at.strftime("%d/%m/%Y %H:%M:%S") %></td>
			<td><%= service.updated_at.strftime("%d/%m/%Y %H:%M:%S") %></td>
			<td><center><%= link_to "Expenses",service_expenses_path(service)%></center></td>
			<td><center><%=link_to "Edit", edit_service_path(service)%></center> </td>
			 
			
		
	<% end %>
</table>
<%#= will_paginate @services %>

app/views/services/new.html.erb
<h1> New Service </h1>

<%= render 'form' %>

app/views/services/show.html.erb
<h1>show</h1>

app/views/shared_times/_form.html.erb
<%= form_for(@shared_time) do |f| %>
  <% if @shared_time.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shared_time.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @shared_time.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :month %><br />
    <%= f.select :month,  options_for_select([["","0"],["January","1"],["February","2"],["March","3"],["April","4"],["May","5"],["June","6"],["July","7"],["August","8"],["September","9"],["October","10"],["November","11"],["December","12"]],@shared_time.month) %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :shared_time_user_tokens, "users shared time" %><br />
	    <%= f.text_field :shared_time_user_tokens , "data-pre" => @array_users.to_json %>
		

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shared_times/edit.html.erb
<h1>Editing Shared Time</h1>

<%= render 'form' %>

app/views/shared_times/index.html.erb
<h1>Shared Times</h1>
<div><%=link_to "New", new_shared_time_path%></div>
<table width="100%">
	<tr>
		<th style="background: #A4A4A4">Month</th>
		<th style="background: #A4A4A4">Year</th>
		<th style="background: #A4A4A4">Created at</th>
		<th style="background: #A4A4A4">Updated at</th>
		<th colspan="2" style="background: #A4A4A4">Options</th>
	</tr>
	<% @shared_times.each do |shared_time| %>
    	<tr>
			<td><%=DateTime.new(2000,shared_time.month,1).strftime("%B")  %></td>
			<td><%= shared_time.year %></td>
			<td><%= shared_time.created_at.strftime("%d/%m/%Y %H:%M:%S") %></td>
			<td><%= shared_time.updated_at.strftime("%d/%m/%Y %H:%M:%S") %></td>
			<td><center><%=link_to "Edit", edit_shared_time_path(shared_time)%></center> </td>
			<td></td>
			 
			
		</tr>
	<% end %>
</table>

app/views/shared_times/new.html.erb
<h1> New Shared Time </h1>

<%= render 'form' %>